### ISSUE TITLE
Adding to quicklisp-dist

### ISSUE THREAD

**Issue by digikar99** [s-expressionists/ctype#13]
Can this library be added to quicklisp?

I've another project [polymorphic-functions](https://github.com/digikar99/polymorphic-functions) that I intend to add to quicklisp this month. But it depends on ctype, so ctype would also need to be added.

So, if there are no issues to adding this library to quicklisp, then me or someone could [create the issue on quicklisp-projects](https://github.com/quicklisp/quicklisp-projects/issues).

**Comment by Bike** [comment]
I can't think of any reason not to. I'll file an issue.

**Comment by Bike** [comment]
Oh, I need to slap a license on it. Would you have any problem with CC0 (https://creativecommons.org/publicdomain/zero/1.0/)?

actually, maybe BSD (2) would be better, if for no other reason than to match Eclector

**Comment by digikar99** [comment]
It seems like [CC0 is not recommended for software](https://opensource.stackexchange.com/questions/133/how-could-using-code-released-under-cc0-infringe-on-the-authors-patents) and [BSD2 is almost the same as MIT](https://opensource.stackexchange.com/questions/217/what-are-the-essential-differences-between-the-bsd-and-mit-licences). So, I definitely do not have any issue with BSD2; compatibility with Eclector helps as well.

**Comment by Bike** [comment]
ctype does not include anything patented, so that's not really relevant, but i'll just do bsd2

**Comment by Bike** [comment]
https://github.com/quicklisp/quicklisp-projects/issues/2094
