### ISSUE TITLE
CTYPE= errors RANGE types

### ISSUE THREAD

**Issue by digikar99** [s-expressionists/ctype#15]
In particular, `(ctype= (ctype 'single-float) (ctype 'single-float))` results in:

```lisp
The value
  NIL
is not of type
  NUMBER
when binding SB-KERNEL::X
   [Condition of type TYPE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {10015383B3}>)

Backtrace:
  0: (SB-KERNEL:TWO-ARG-= NIL NIL) [external]
  1: (SB-VM::GENERIC-=)
  2: ((:METHOD CTYPE= (RANGE RANGE)) #<RANGE SINGLE-FLOAT> #<RANGE SINGLE-FLOAT>) [fast-method]
  3: ((SB-PCL::EMF CTYPE=) #<unused argument> #<unused argument> #<RANGE SINGLE-FLOAT> #<RANGE SINGLE-FLOAT>)
```

I think the problem is `parse-interval-designator` returning NIL, which then gets used by the `ctype=` method, but sure if there are other ways to fix this:

https://github.com/s-expressionists/ctype/blob/563a287bce26ac69d8eb2306e71ffa0794716f84/parse.lisp#L69-L75

https://github.com/s-expressionists/ctype/blob/563a287bce26ac69d8eb2306e71ffa0794716f84/range.lisp#L35-L41

**Comment by Bike** [comment]
`nil` is allowed there, it means no bound. `ctype=` did not handle this properly (at all).

**Comment by digikar99** [comment]
My initial guess was that this would be `T T`, but it happens to be `NIL T`:

```lisp
CL-USER> (alexandria:type= `(single-float ,most-negative-single-float ,most-positive-single-float)
                           `(single-float))
NIL
T
```

So, alright, it seems like it is CTYPE= that is required to handle it appropriately rather than PARSE-INTERVAL-DESIGNATOR.

**Comment by Bike** [comment]
Every Lisp implementation I know of uses IEEE 754 floats, which have infinities and NaNs that may be part of the unbounded type but not the bounded type.
