### ISSUE TITLE
Add plist type and other fun stuff

### ISSUE THREAD

**Issue by githubforced2fabad** [s-expressionists/ctype#29]
I have trouble with github pull requests (see username); thank you for being patient. 

Here are some changes I have worked on
- plist type (discussed on IRC)
- subctype ccons clist-of (discussed on IRC)
- export sub-lambda-list-p (I need this exported for a project of mine)

If you like the changes, you can pull from this remote: [https://git.sr.ht/~charje/ctype](https://git.sr.ht/~charje/ctype).

Alternatively here are some patch files that you can apply.
[0001-Allow-ccons-to-be-subctype-of-clist-of.txt](https://github.com/user-attachments/files/15746133/0001-Allow-ccons-to-be-subctype-of-clist-of.txt)
[0002-Export-sub-lambda-list-p.txt](https://github.com/user-attachments/files/15746134/0002-Export-sub-lambda-list-p.txt)
[0003-Add-plist-type.txt](https://github.com/user-attachments/files/15746135/0003-Add-plist-type.txt)

**Comment by Bike** [comment]
changes look fine to me. i will merge them in a bit.

While looking through the data structures code I have realized that we should probably canonicalize `(and (clist-of X) (clist-of Y))` to `null` when X and Y are disjoint, so I"ll put that in too. Provided I can remember that it should be `null` rather than `nil`.

**Comment by githubforced2fabad** [comment]
Cool. Thank you for taking a look. I ran into the disjoint list-of too, but I forgot to ask about it and fix it.

**Comment by Bike** [comment]
Merged as https://github.com/s-expressionists/ctype/commit/c514623a0cd5c4340ab4ab13d90509f15f09c47a (and ancestor commits).

**Comment by githubforced2fabad** [comment]
Here is a little follow up to this. After some light manual testing, I realized that I had missed one of the local variables when renaming some things. Here is a small patch to fix it. It also clarifies some a docstring. I have also updated my fork https://git.sr.ht/~charje/ctype in case you would rather pull instead of applying patches.

[0001-Fix-property-key-variable-name.txt](https://github.com/user-attachments/files/15860255/0001-Fix-property-key-variable-name.txt)

**Comment by githubforced2fabad** [comment]
Does this look okay to you?

**Comment by jgarte** [comment]
Hi, what's the status on this issue?

**Comment by Bike** [comment]
done. I did it quick and manually so let me know if there are any more issues. Sorry for the delay.
