### ISSUE TITLE
Potential bug in function types

### ISSUE THREAD

**Issue by alex-gutev** [s-expressionists/ctype#5]
Converting a `FUNCTION` type specifier, with a lambda-list in which one or more of the arguments are `*`, results in an error condition being signalled.

Evaluating the following at the REPL:
```lisp
(ctype:specifier-ctype '(function (*) t))
```
Results in:
```
debugger invoked on a SB-PCL:CLASS-NOT-FOUND-ERROR in thread
#<THREAD "main thread" RUNNING {10005505B3}>:
  There is no class named COMMON-LISP:*.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.```
```
There is no issue if the entire lambda-list is `*`:

```
* (ctype:specifier-ctype '(function * t))
#<CTYPE:CFUNCTION FUNCTION>
```
Theoretically a function type specifier with a `*` in the lambda-list is valid.

Environment details:
* SBCL 2.1.4

**Comment by Bike** [comment]
My understanding of the standard is that `*` is not a type specifier, but may be used as an argument to some compound type specifiers in certain fixed ways, not including as a parameter in a lambda list. Is there code that does this? Why not just use `t`?

**Comment by alex-gutev** [comment]
I'm too not sure about this myself, and the spec isn't exactly clear. It doesn't explicitly state that `*` is allowed in function type lambda-lists, however neither does it state that it's not. SBCL seems to accept code with type declarations such as the following `(function (*) *)` without errors or warnings.
I opened this issue because it's possible that `function-information`, from CLTL2, may return an `FTYPE` with a `*` in the lambda-list, however if it's forbidden by the standard then there is no need.

**Comment by Bike** [comment]
Well, if this isn't just a theoretical issue it may be worthwhile allowing `*` more liberally

**Comment by alex-gutev** [comment]
I don't know if this issue will crop up in practice but there is that possibility.

**Comment by alex-gutev** [comment]
I guess SBCL no longer accepts `*` in the parameter list of `function` type specifiers, as of version 2.1.10, so we can safely close this issue.
