### ISSUE TITLE
CFUNCTION's %RETURNS slot is of type CVALUES

### ISSUE THREAD

**Issue by digikar99** [s-expressionists/ctype#9]
I'm not sure about the semantics therefore not issues a PR. 

`(ctype:specifier-ctype 'function)` errors on CCL:

> The value #<CONJUNCTION T>, derived from the initarg :RETURNS, can not be used to set the value of the slot CTYPE::%RETURNS in #<CFUNCTION #<error printing CTYPE:CFUNCTION #x30200105C0DD>, because it is not of type CTYPE:CVALUES.

This stems from `rv` taking the value `(top)` not of type `cvalues` ([here](https://github.com/s-expressionists/ctype/blob/5ecfb217df9448e030196e372ca5df272e042801/parse.lisp#L206)) while `%returns` slot of class `cfunction` is declared to be of type `cvalues` ([here](https://github.com/s-expressionists/ctype/blob/5ecfb217df9448e030196e372ca5df272e042801/classes.lisp#L104)). This is a non-issue on SBCL since it seems to ignore this type check at least at the default safety level 1, but errors at safety level 3.

**Comment by digikar99** [comment]
Also, SBCL:

```lisp
CL-USER> (subtypep '(function * (values &optional)) '(function * t))
T
T
CL-USER> (subtypep '(function * t) '(function * (values &optional)))
NIL
T
```

**Comment by Bike** [comment]
`(ctype:specifier-ctype 'function)` should obviously not signal an error, semanticswise.

As for what to do... the parser ought to normalize it into a values ctype, I think. You could still write `(function * t)`, it would just mean the same as `(function * (values t &rest t))`.

Values types in general are pretty weird. My interpretation of how to treat them is a bit different from SBCL's.

**Comment by digikar99** [comment]
On SBCL, the following does hold:

```lisp
CL-USER> (subtypep '(function * *) '(function * (values &rest t)))
T
T
CL-USER> (subtypep '(function * (values &rest t)) '(function * *))
T
T
```

So, the `(eq rv '*)` case could be normalized to `(cvalues nil nil (top))`... erm... should [cvalues return (top)](https://github.com/s-expressionists/ctype/blob/5ecfb217df9448e030196e372ca5df272e042801/create.lisp#L69)?

And yes, the other case, when `(eq rv '*)` does not hold, that should be ensured to be a `cvalues` type (?)

**Comment by Bike** [comment]
Could you verify that this fix works? I can do `(specifier-ctype 'function)` in ccl no problem now.

**Comment by digikar99** [comment]
This doesn't error now, but:

```lisp
CL-USER> (subtypep 'function '(function * (values &rest t)))
T
T
CL-USER> (subtypep 'function '(function * (values t &rest t)))
NIL
T
CL-USER> (ctype:specifier-ctype 'function)
#<CTYPE:CFUNCTION (FUNCTION * (VALUES T &REST T))>
CL-USER> (ctype:unparse (ctype:cfunction-returns (ctype:specifier-ctype 'function)))
(VALUES T &REST T)
```

**Comment by Bike** [comment]
`(ctype:unparse (ctype:cfunction-returns (ctype:specifier-ctype 'function)))` is `(values &rest t)` for me in both sbcl and ccl. I don't know why that would be different from what you have.

`(values t &rest t)` means at least one value, whereas `(values &rest t)` is at least zero values, so the latter is not a subtype of the former, I think.

**Comment by digikar99** [comment]
> `(ctype:unparse (ctype:cfunction-returns (ctype:specifier-ctype 'function)))` is `(values &rest t)` for me in both sbcl and ccl.

Okay, apologies, something was wrong at my end. This works as expected.
